export const myProjects = [
  {
    title: "Red Onion",
    description:
      "Instagram clone built using Next JS, Typescript, and TailwindCSS. This web application was built solely for research purposes and not for any malicious intent.",
    img: "/media/images/red-onion.jpeg",
    tags: ["ReactJS", "React Bootstrap", "Firebase"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/red-onion",
    left: true,
  },
  {
    title: "Logo Tech",
    description:
      "Enhance your logo with our technology that helps you to get appropriate logo for your business. Which seamlessly grab attention of vendors.",
    img: "/media/images/logo-tech.jpg",
    tags: ["ReactJS", "Tailwind CSS", "Firebase"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/logo-tech",
    left: false,
  },
  {
    title: "Creative Agency",
    description:
      "Recreate agencies with their user or local policy that helps them to identify with proper optimistic agency to threshold and convey user with trust.",
    img: "/media/images/creative-agency.png",
    tags: ["ReactJS", "Express", "MongoDB", "Firebase", "React Bootstrap"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/creative-agency-client",
    left: true,
  },
  {
    title: "Luxury Living",
    description:
      "Reinvent your luxury with luxury services that allow you to retain us with your daily life that make easier to obey your luxury through our website.",
    img: "/media/images/luxuryliving.png",
    tags: ["NextJS", "Express", "MongoDB", "Firebase", "DaisyUI"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/luxury-living-client",
    left: false,
  },
  {
    title: "Doctors Portal",
    description:
      "It is a doctors portal appointment based web application or website which simply construct with all need with a doctor and with a patient like making realtime appointment with a doctor.",
    img: "/media/images/doctors-portal.jpeg",
    tags: ["ReactJS", "Express", "MongoDB", "Firebase", "DaisyUI"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/doctors-portal-client",
    left: true,
  },
  {
    title: "Arsha",
    description:
      "It's solution based website which provide multi-types solutions in business to scale it as a next level concern. But this is a static website which radially used for display as a project but as taking ideas it's literally best.",
    img: "/media/images/arsha.png",
    tags: ["HTML5", "CSS3", "Bootstrap 5"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/demo-arsha",
    left: false,
  },
  {
    title: "Bethany",
    description:
      "It's an online attendence blooming website which institute used for presence of their own to engage with greet valley. Get obsolate token wheather necessery.Used to display the samplistic idea as own.",
    img: "/media/images/bethany.png",
    tags: ["HTML5", "CSS3", "Bootstrap 5"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/demo-bethany",
    left: true,
  },
  {
    title: "Moderna",
    description:
      "It's an online attendence blooming website which institute used for presence of their own to engage with greet valley. Get obsolate token wheather necessery.Used to display the samplistic idea as own.",
    img: "/media/images/moderna.png",
    tags: ["HTML5", "CSS3", "Bootstrap 5"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/demo-mordana",
    left: false,
  },
  {
    title: "The Event",
    description:
      "It's an event organizing or event insperation website. Which can obey an event and represent it's sweet and anguler options which although can retain the semantics of any location.",
    img: "/media/images/the-event.png",
    tags: ["HTML5", "CSS3", "Bootstrap 5"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/demo-theEvent",
    left: true,
  },
  {
    title: "Travel Guru",
    description:
      "It's a travel management minimal website that not gonna used by professional. Although it is hobby testing site just figure out the functionality to convey with localStorage as a sense and conduct.",
    img: "/media/images/travel-guru.jpeg",
    tags: ["ReactJS", "Material UI", "Firebase", "React-router"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/travel-guru",
    left: false,
  },
  {
    title: "TSC",
    description:
      "It's a full database website base on teacher student center. Which concludes an attendance type cemetery. That allows student to add notes like do in note app and also allows to do minimally for a teacher to add or remove student.",
    img: "/media/images/teacher-student-center.jpg",
    tags: [
      "ReactJS",
      "Tailwind CSS",
      "HTML-TO-Excel",
      "Hook-Form",
      "ExpressJS",
      "MongoDB",
      "NodeJS",
    ],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/tsc-client",
    left: true,
  },
  {
    title: "Node Chat Application",
    description:
      "A full stack project which is now deprecated. And not able to give other way support right now and not eligible to have best out of it. As a tough project it's technology getting old and wisher support getting deprecated therefore no running state on it.",
    img: "/media/images/node-chat-app.png",
    tags: ["NodeJS", "JWT", "MongoDB", "EJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/node-chat-application",
    left: false,
  },
  {
    title: "Create random user API",
    description:
      "A full stack project which is now activated. And able to give other way support right now and not eligible to have best out of it. As a tough project it's technology getting old and wisher support getting not deprecated therefore no running state on it.",
    img: "/media/images/random-user-api.png",
    tags: ["Postman", "NodeJS", "ES6", "LOCAL DB", "HTML5", "ExpressJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/random-user-api",
    left: true,
  },
  {
    title: "Directory of books",
    description:
      "A full stack project which is now activated. And able to give other way support right now and not eligible to have best out of it. As a tough project it's technology getting old and wisher support getting not deprecated therefore no running state on it.",
    img: "/media/images/directory-books.png",
    tags: ["Postman", "NodeJS", "ES6", "LOCAL DB", "HTML5", "ExpressJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/random-user-api",
    left: false,
  },
  {
    title: "Simple cart system",
    description:
      "A frontend project as an assignment to be given where main purpose is a complete cart system going to be thrown as a realistic materialism. The idea is to create a Product Listing page and cart (checkout) summary page of an ecommerce website which has certain functionalities.",
    img: "/media/images/simple-cart.png",
    tags: ["ES6", "CSS3", "HTML5", "ReactJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/toothsi-reactjs-assignment",
    left: true,
  },
  {
    title: "Simple todo",
    description:
      "A frontend project as an assignment to be given where main purpose is a complete cart system going to be thrown as a realistic materialism. Simple todo based on Localstorage approach that going to saved upto files at visibility to UI directly.",
    img: "/media/images/simple-todo.png",
    tags: ["ES6", "CSS3", "HTML5", "ReactJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/simple-todo",
    left: false,
  },
  {
    title: "Simple file upload",
    description:
      "A frontend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Using Multer.JS to store files to direct store on Heroku and convey upto there as a store.",
    img: "/media/images/simple-file-upload.png",
    tags: ["ES6", "CSS3", "HTML5", "ReactJS", "Daisy UI"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/simple-multer-file-upload-client",
    left: true,
  },
  {
    title: "Tour management system",
    description:
      "A backend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Using Multer.JS to store files to direct store on Heroku and convey upto there as a store.",
    img: "/media/images/tour-management-system.png",
    tags: ["Postman", "NodeJS", "ES6", "MongoDB", "HTML5", "ExpressJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/tour-management-system",
    left: false,
  },
  {
    title: "Inventory management system",
    description:
      "A backend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/inventory-management-system.png",
    tags: ["Postman", "NodeJS", "ES6", "MongoDB", "HTML5", "ExpressJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/inventory-management-system3",
    left: true,
  },
  {
    title: "QR code generator",
    description:
      "A frontend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/qr-generator.png",
    tags: ["ES6", "CSS3", "HTML5", "JavaScript"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/qr-code-generator",
    left: false,
  },
  {
    title: "50 days 50 project",
    description:
      "A frontend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/50-by-50-projects.png",
    tags: ["ES6", "CSS3", "HTML5", "JavaScript"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/50_projects-50_days",
    left: true,
  },
  {
    title: "Data Structure and Algorithm with JavaScript",
    description:
      "A combined project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/dsa-js.png",
    tags: [
      "sorting",
      "algorithm",
      "brutforces",
      "backtracking",
      "dfs",
      "bfs",
      "problem solving",
      "dsa",
      "javascript",
    ],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/dsa-js",
    left: false,
  },
  {
    title: "Codeforces judge competition",
    description:
      "A combined project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/dsa-js.png",
    tags: ["c++", "codeforces"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/CodeForces-online-judge",
    left: true,
  },
  {
    title: "URI online judge",
    description:
      "A combined project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/uri-online-judge.png",
    tags: [
      "js",
      "ruby",
      "kotlin",
      "java",
      "go",
      "dart",
      "golang",
      "pascal",
      "clojure",
      "haskell",
      "scala",
      "lua",
      "c#",
      "ocmal",
      "uri online judge",
      "beecrowd",
    ],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/URI-online-judge",
    left: false,
  },
  {
    title: "Uptime monitoring API",
    description:
      "A backend project as an assignment to be given where main purpose is a complete file upload system going to be thrown as a realistic materialism. Managing store with it's full potential as it going to convey through.",
    img: "/media/images/up-time-monitoring.png",
    tags: ["Postman", "NodeJS", "ES6", "LOCAL DB", "HTML5", "ExpressJS"],
    cta: "View Project",
    url: "https://github.com/hasibulislam999/uptime-monitoring-api",
    left: true,
  },
  {
    title: "SkillNao LMS Project",
    description:
      "A fullstack paid project that going to applied on a lms business topology in Bangladesh. Where student going to get advised throughout professionals and successful students that help student to build a heavy passion with more inheritance approach politely weather it's going to be filled up by the way repo won't given as per paid so as per confidential to prologuize it.",
    img: "/media/images/skill-nao.png",
    tags: [
      "ReactJS",
      "NodeJS",
      "ES6",
      "Mongo DB",
      "HTML5",
      "CSS3",
      "ExpressJS",
      "Mongoose",
      "Cloudinary",
      "skill-nao"
    ],
    cta: "View Project",
    url: "https://skillnao-csr.vercel.app/",
    left: false,
  },
];
